-- HOUSECONNECT PRO / SUPABASE DATABASE SCHEMA
-- TIMESTAMP: 2026-02-28
-- WARNING: This schema is for tracking current application architecture. 
-- Do not run in production unless absolutely necessary, to avoid breaking any current functionality.

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. USERS TABLE (Handled by Supabase Auth, but good practice to map an external profile table)
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. CONTRACTORS TABLE
CREATE TABLE IF NOT EXISTS public.contractors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    service TEXT NOT NULL, -- e.g., 'Plumbing', 'Electrical'
    rating NUMERIC(3,2) DEFAULT 0.0,
    reviews INTEGER DEFAULT 0,
    price TEXT, -- e.g., '₹450/hr' OR integer floor depending on how we compute
    image TEXT, -- URL or emoji string indicator
    available BOOLEAN DEFAULT true,
    verified BOOLEAN DEFAULT false,
    location TEXT, -- e.g., 'Nagpur, Maharashtra'
    response_time TEXT, -- e.g., '~30 min'
    completed_jobs INTEGER DEFAULT 0,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. JOBS TABLE (Posted by Homeowners)
CREATE TABLE IF NOT EXISTS public.jobs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    location TEXT NOT NULL,
    urgency TEXT NOT NULL,
    budget_min INTEGER,
    budget_max INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. BOOKINGS TABLE (Connecting Users and Contractors)
CREATE TABLE IF NOT EXISTS public.bookings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    contractor_id BIGINT REFERENCES public.contractors(id) ON DELETE SET NULL, -- Contractor might be deleted, but keep record
    date DATE NOT NULL,
    time TEXT NOT NULL,
    notes TEXT,
    status TEXT DEFAULT 'pending', -- 'pending', 'upcoming', 'completed', 'cancelled'
    price INTEGER, -- Stored as fixed integer for the booking
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. DISPUTES TABLE (Resolution Hub)
CREATE TABLE IF NOT EXISTS public.disputes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    booking_id UUID REFERENCES public.bookings(id) ON DELETE SET NULL,
    type TEXT NOT NULL, -- 'refund', 'quality', 'noshow'
    description TEXT NOT NULL,
    status TEXT DEFAULT 'In Review', -- 'In Review', 'Resolved', 'Closed'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ROW LEVEL SECURITY (RLS) POLICIES
-- NOTE: Enable these only when DB is fully active and tested

-- Enable RLS on all tables
-- ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.contractors ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.disputes ENABLE ROW LEVEL SECURITY;

-- User Policies
-- CREATE POLICY "Users can view their own profile" ON public.users FOR SELECT USING (auth.uid() = id);
-- CREATE POLICY "Users can update their own profile" ON public.users FOR UPDATE USING (auth.uid() = id);

-- Contractor Policies
-- CREATE POLICY "Everyone can view contractors" ON public.contractors FOR SELECT USING (true);
-- CREATE POLICY "Authenticated users can create contractors (Post Job)" ON public.contractors FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Jobs Policies
-- CREATE POLICY "Everyone can view jobs" ON public.jobs FOR SELECT USING (true);
-- CREATE POLICY "Users can insert their own jobs" ON public.jobs FOR INSERT WITH CHECK (auth.uid() = user_id);
-- CREATE POLICY "Users can edit their own jobs" ON public.jobs FOR UPDATE USING (auth.uid() = user_id);
-- CREATE POLICY "Users can delete their own jobs" ON public.jobs FOR DELETE USING (auth.uid() = user_id);

-- Booking Policies
-- CREATE POLICY "Users can view their own bookings" ON public.bookings FOR SELECT USING (auth.uid() = user_id);
-- CREATE POLICY "Users can insert their own bookings" ON public.bookings FOR INSERT WITH CHECK (auth.uid() = user_id);
-- CREATE POLICY "Users can update their own bookings" ON public.bookings FOR UPDATE USING (auth.uid() = user_id);

-- Dispute Policies
-- CREATE POLICY "Users can view their own disputes" ON public.disputes FOR SELECT USING (auth.uid() = user_id);
-- CREATE POLICY "Users can create their own disputes" ON public.disputes FOR INSERT WITH CHECK (auth.uid() = user_id);

-- REALTIME CONFIGURATION
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.bookings;
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.disputes;
