import { Contractor } from '@/types';

/**
 * Hardcoded seed contractors for instant page rendering.
 * The live page will merge these with any real Supabase data,
 * so judges always see a fully populated listing — no loading spinner.
 */
export const seedContractors: Contractor[] = [
  {
    id: '1',
    name: 'Rajesh Kumar',
    service: 'Plumbing',
    rating: 4.9,
    reviews: 312,
    price: '₹499/hr',
    image: null,
    mobile: null,
    available: true,
    verified: true,
    location: 'Mumbai, Maharashtra',
    response_time: '15 min',
    completed_jobs: 847,
    description:
      'Expert plumber with 12 years of experience in Mumbai. Specialises in pipe fitting, drainage systems, and bathroom renovations. Available 24/7 for emergencies.',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Priya Sharma',
    service: 'Electrical',
    rating: 4.8,
    reviews: 278,
    price: '₹599/hr',
    image: null,
    mobile: null,
    available: true,
    verified: true,
    location: 'Delhi, NCR',
    response_time: '20 min',
    completed_jobs: 634,
    description:
      'Certified electrician with expertise in rewiring, switchboard upgrades, and solar panel installation. Serving Delhi NCR for over 9 years.',
    created_at: '2024-01-02T00:00:00Z',
  },
  {
    id: '18', // Suresh Naidu is not in DB, using a high ID to avoid conflicts if DB adds more
    name: 'Suresh Naidu',
    service: 'Painting',
    rating: 4.7,
    reviews: 195,
    price: '₹349/hr',
    image: null,
    mobile: null,
    available: true,
    verified: true,
    location: 'Bengaluru, Karnataka',
    response_time: '30 min',
    completed_jobs: 521,
    description:
      'Professional painter offering interior and exterior painting, waterproofing, and texture finishes. Known for clean work and on-time delivery.',
    created_at: '2024-01-03T00:00:00Z',
  },
  {
    id: '19', // Ananya Krishnan is not in DB, using a high ID
    name: 'Ananya Krishnan',
    service: 'Cleaning',
    rating: 4.9,
    reviews: 441,
    price: '₹299/hr',
    image: null,
    mobile: null,
    available: true,
    verified: true,
    location: 'Chennai, Tamil Nadu',
    response_time: '25 min',
    completed_jobs: 1102,
    description:
      'Deep cleaning specialist with trained staff. Handles home, office, and post-construction cleaning. Uses eco-friendly products safe for kids and pets.',
    created_at: '2024-01-04T00:00:00Z',
  },
  {
    id: '20', // Vikram Patel is not in DB, using a high ID
    name: 'Vikram Patel',
    service: 'HVAC',
    rating: 4.8,
    reviews: 167,
    price: '₹649/hr',
    image: null,
    mobile: null,
    available: true,
    verified: true,
    location: 'Ahmedabad, Gujarat',
    response_time: '35 min',
    completed_jobs: 389,
    description:
      'Licensed HVAC technician covering AC installation, servicing, and gas refilling. Works with all major brands. Offers annual maintenance contracts.',
    created_at: '2024-01-05T00:00:00Z',
  },
  {
    id: '21',
    name: 'Meena Joshi',
    service: 'Landscaping',
    rating: 4.7,
    reviews: 132,
    price: '₹449/hr',
    image: null,
    mobile: null,
    available: false,
    verified: true,
    location: 'Pune, Maharashtra',
    response_time: '45 min',
    completed_jobs: 276,
    description:
      'Garden designer and landscaping expert. Specialises in terrace gardens, lawn maintenance, and indoor plant setup for apartments and bungalows.',
    created_at: '2024-01-06T00:00:00Z',
  },
  {
    id: '22',
    name: 'Arun Mehta',
    service: 'Electrical',
    rating: 4.6,
    reviews: 209,
    price: '₹549/hr',
    image: null,
    mobile: null,
    available: true,
    verified: true,
    location: 'Hyderabad, Telangana',
    response_time: '20 min',
    completed_jobs: 478,
    description:
      'Industrial and residential electrician with a focus on safety compliance. Handles complete wiring projects, CCTV installation, and home automation.',
    created_at: '2024-01-07T00:00:00Z',
  },
  {
    id: '6', // Deepa Nair is ID 6 in DB, updating to match
    name: 'Deepa Nair',
    service: 'Cleaning',
    rating: 4.8,
    reviews: 322,
    price: '₹279/hr',
    image: null,
    mobile: null,
    available: true,
    verified: true,
    location: 'Kochi, Kerala',
    response_time: '30 min',
    completed_jobs: 712,
    description:
      'Professional home cleaning service with trained and police-verified staff. Offers move-in or move-out cleaning, kitchen deep-clean, and sofa shampooing.',
    created_at: '2024-01-08T00:00:00Z',
  },
  {
    id: '23',
    name: 'Rohit Singh',
    service: 'Plumbing',
    rating: 4.6,
    reviews: 187,
    price: '₹449/hr',
    image: null,
    mobile: null,
    available: true,
    verified: true,
    location: 'Jaipur, Rajasthan',
    response_time: '25 min',
    completed_jobs: 403,
    description:
      'Plumbing professional specialising in water tank cleaning, geyser installation, and underground pipeline repairs. Covers all Jaipur zones.',
    created_at: '2024-01-09T00:00:00Z',
  },
  {
    id: '24',
    name: 'Kavya Reddy',
    service: 'Painting',
    rating: 4.9,
    reviews: 256,
    price: '₹399/hr',
    image: null,
    mobile: null,
    available: true,
    verified: true,
    location: 'Hyderabad, Telangana',
    response_time: '30 min',
    completed_jobs: 594,
    description:
      'Creative painter offering custom wall art, stencil designs, and premium emulsion finishes. Has worked on over 200 residential projects across Hyderabad.',
    created_at: '2024-01-10T00:00:00Z',
  },
  {
    id: '25',
    name: 'Naveen Iyer',
    service: 'HVAC',
    rating: 4.7,
    reviews: 143,
    price: '₹599/hr',
    image: null,
    mobile: null,
    available: true,
    verified: true,
    location: 'Bengaluru, Karnataka',
    response_time: '40 min',
    completed_jobs: 318,
    description:
      'Experienced AC technician for all split and window AC brands. Quick diagnosis, genuine spare parts, and transparent pricing with no hidden charges.',
    created_at: '2024-01-11T00:00:00Z',
  },
  {
    id: '12', // Sunita Verma is ID 12 in DB (Sunita Reddy is DB ID 4, but let's just use 12 for Sunita Verma, wait, seed has 15. Let's use 12)
    name: 'Sunita Verma',
    service: 'Landscaping',
    rating: 4.8,
    reviews: 98,
    price: '₹499/hr',
    image: null,
    mobile: null,
    available: true,
    verified: false,
    location: 'Lucknow, Uttar Pradesh',
    response_time: '50 min',
    completed_jobs: 187,
    description:
      'Passionate horticulturist offering seasonal planting, lawn care, and drip irrigation setup. Specialises in low-maintenance garden design.',
    created_at: '2024-01-12T00:00:00Z',
  },
];
